# Generated by Django 3.2.3 on 2021-09-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0002_geolocation_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geolocation',
            old_name='country',
            new_name='country_name',
        ),
        migrations.AddField(
            model_name='geolocation',
            name='city',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geolocation',
            name='continent_name',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geolocation',
            name='latitude',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geolocation',
            name='longitude',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geolocation',
            name='region_name',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geolocation',
            name='zip',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
